source 'https://rubygems.org'

gem 'rails', '~> 6.0.0.rc1'
gem 'sqlite3'
gem 'unicorn'
gem 'sass'
gem 'sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'carrierwave'
gem 'mini_magick', '>= 4.9.4'
gem 'bootstrap', '~> 4.3.1'
gem 'tinymce-rails', '~> 4.0'
gem 'tinymce-rails-imageupload', '~> 4.0.0.beta'
gem 'execjs'
gem 'mini_racer'
group :development do
  gem 'listen', '~> 3.0.5'
  gem 'solargraph'
  gem 'rufo'
  gem 'capistrano', '~> 3.11'
  gem 'capistrano-rails', '~> 1.4'
  gem 'capistrano-passenger', '~> 0.2.0'
  gem 'capistrano-rbenv', '~> 2.1', '>= 2.1.4'
end
