source 'https://rubygems.org'

gem 'rails', '~> 6.0.0.rc1'
gem 'pg'
gem 'unicorn'
gem 'sass'
gem 'sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'carrierwave'
gem 'carrierwave-postgresql', '0.3.0'
gem 'postgresql_lo_streamer'
gem 'mini_magick', '>= 4.9.4'
gem 'bootstrap', '~> 4.3.1'
gem 'figaro'
gem 'tinymce-rails'
gem 'execjs'
gem 'mini_racer'
group :development do
  gem 'listen', '~> 3.0.5'
  gem 'solargraph'
end
